### ISSUE TITLE
DOT Matrix support

### ISSUE THREAD

**Issue by rhymelph** [Im-Kevin/rare_print#2]
DOT Matrix support

**Comment by Im-Kevin** [comment]
可以详细讲讲怎么个支持吗

**Comment by rhymelph** [comment]
https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=6737&scat=61&pcat=5

**Comment by Im-Kevin** [comment]
有相关指令集吗

**Comment by rhymelph** [comment]
跟esc-pos 指令差不多,哈哈

**Comment by rhymelph** [comment]
#1

**Comment by Im-Kevin** [comment]
这个我有讲的,目前在尝试使用点阵模式输出,但是编译出的指令太大了,在想办法优化
